spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # create: 앱 실행 시 테이블 삭제 후 재생성 (개발용)
    properties:
      hibernate:
        format_sql: true # SQL 보기 좋게 출력
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug # 실행되는 SQL 출력
    # 아래 중 하나 선택 (SQL 바인딩 값 출력용):
    # org.hibernate.type: trace            # 스프링 부트 2.x / Hibernate 5.x
    # org.hibernate.orm.jdbc.bind: trace   # 스프링 부트 3.x / Hibernate 6.x
